# Generated by Django 5.1.1 on 2024-10-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_student_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='dean',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='number_of_departments',
        ),
    ]
